[package]
authors = ["Willem Wyndham <willem@near.org>"]
edition = "2021"
name = "near-riffs-registry"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-riffs = { path = "../.." }
near-riffs-core = { path = "../core" }

[package.metadata.witgen]
export = true
