[package]
edition = "2021"
name = "near-riffs-admins"
version = "0.1.0"
publish = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-riffs = {path = "../.."}
near-riffs-core = {path = "../core"}
microjson = "0.1.0"

[features]
wee_alloc = ["near-riffs/wee_alloc"]
